# Generated by Django 5.0 on 2023-12-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_alter_movie_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='youtube_iframe',
            field=models.URLField(blank=True),
        ),
    ]
