# Generated by Django 5.0 on 2023-12-31 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_movie_youtube_iframe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='youtube_iframe',
            new_name='iframe',
        ),
    ]
