# Generated by Django 5.0 on 2023-12-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_rename_youtube_iframe_movie_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='iframe',
            field=models.TextField(blank=True),
        ),
    ]
