# Generated by Django 5.0 on 2023-12-31 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_alter_movie_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='iframe',
            field=models.CharField(blank=True, max_length=250, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
