# Generated by Django 5.0 on 2024-01-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_alter_movie_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='iframe',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
