# Generated by Django 5.0 on 2024-01-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='request',
            new_name='message',
        ),
    ]
